
pipe: pipe.c
	gcc pipe.c -o pipe

fifo: user1.c user2.c
	gcc user1.c -o user1
	gcc user2.c -o user2

q1:	q1.c
	gcc q1.c -o q1


q3:	q3.c
	gcc q3.c -o q3

q4:	q4.c
	gcc q4.c -o q4

msg: fifoMsg.c
	gcc fifoMsg.c -o fifoMsg